name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Install vcpkg dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential tar curl zip unzip ninja-build
    
    - name: Build vcpkg
      run: |
        cd $HOME
        git clone https://github.com/microsoft/vcpkg
        vcpkg/bootstrap-vcpkg.sh -disableMetrics
        
    - name: Install catch2
      run: |
        cd $HOME
        vcpkg/vcpkg install catch2
      
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: CXX=clang++-10 CC=clang10 cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake -G "Ninja"

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE
