name: Release with tests

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - {
              name: "Linux: build with gcc",
              os: ubuntu-20.04,
              vcpkg_root: "/usr/local/share/vcpkg",
              cc: "gcc-10", cxx: "g++-10"
            }
          - {
              name: "Linux: build with clang",
              os: ubuntu-20.04,
              vcpkg_root: "/usr/local/share/vcpkg",
              cc: "clang-10", cxx: "clang++-10"
            }
          - {
              name: "macOS: build with clang",
              os: macos-latest,
              vcpkg_root: "/usr/local/share/vcpkg",
              cc: "/usr/local/opt/llvm/bin/clang",
              cxx: "/usr/local/opt/llvm/bin/clang++",
              cxx_flags: "-stdlib=libc++"
            }

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies (Linux)
      if: startsWith(matrix.config.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install build-essential ninja-build build-essential g++-10

    - name: Install dependencies (macOS)
      if: startsWith(matrix.config.os, 'macos')
      run: |
        brew update
        brew install ninja

    - name: Install catch2
      working-directory: ${{ env.HOME }}
      run: vcpkg install catch2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
        CXX=${{ matrix.config.cxx }} CC=${{ matrix.config.cc }} \
        cmake $GITHUB_WORKSPACE \
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
        -DCMAKE_TOOLCHAIN_FILE=${{ matrix.config.vcpkg_root }}/scripts/buildsystems/vcpkg.cmake \
        -D "CMAKE_CXX_FLAGS:STRING=${{ matrix.config.cxx_flags }}"
        -G "Ninja"

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE
